### ISSUE TITLE
 Python version?

### ISSUE THREAD

**Issue by orchid00** [monash-merc/asynchy#12]
* Python version: 
* Operating System: Linux 

What version of Python is expected to install the software?
https://asynchy.readthedocs.io/en/latest/installation.html

**Comment by manishkumr** [comment]
Hi @orchid00 ,

The supported python version are listed here in setup.py:
https://github.com/monash-merc/asynchy/blob/e94bb9a301a00a107edaaa3a3f9363655b194fb5/setup.py#L24
